dist: trusty
os: linux
language: php
php:
- '7.2'
services:
- mysql
install:
- mysql -e 'CREATE DATABASE aurora;'
- composer self-update 1.10.20
- composer install
- composer run pre-config
script:
- php ./travis.php
- chmod +x ./travis.sh
- ./travis.sh -t npm
- ./travis.sh -t build
after_success: 
- ./travis.sh -t pack
- ./travis.sh -t upload
env:
  global:
  - PRODUCT_NAME=aurora-corporate
  
