dist: trusty
os: linux
language: php
php:
- '7.1.14'
services:
- mysql
install:
- mysql -e 'CREATE DATABASE aurora;'
- composer install
- composer run pre-config
- npm install -g newman
script:
- php ./travis.php
- chmod +x ./travis.sh
- ./travis.sh -t build
after_success: 
- ./travis.sh -t pack
- ./travis.sh -t upload
env:
  global:
  - PRODUCT_NAME=aurora-corporate
  